"""create_initial_schema_and_audit_events

Revision ID: 38d51baa66da
Revises: 
Create Date: 2026-10-07 08:48:04.425434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d51baa66da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_id'), ['id'], unique=False)
        batch_op.create_index('ix_audit_events_type_created', ['event_type', 'created_at'], unique=False)

    with op.batch_alter_table('risk_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_risk_alerts_status_score', ['status', 'score'], unique=False)

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index('ix_transfers_receiver_created', ['receiver_id', 'created_at'], unique=False)
        batch_op.create_index('ix_transfers_sender_created', ['sender_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index('ix_transfers_sender_created')
        batch_op.drop_index('ix_transfers_receiver_created')

    with op.batch_alter_table('risk_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_alerts_status_score')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_type_created')
        batch_op.drop_index(batch_op.f('ix_audit_events_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
